### ISSUE TITLE
Streaming Apache Avro (Question, not a bug)

### ISSUE THREAD

**Issue by stuartweir** [flavray/avro-rs#141]
Hi there!

I'm newer to rust, but I have a bit of experience working in the language now (I'm currently writing a Proof of Concept in the language), and I'm considering using Avro as my defacto data format to store data I want to run calculations on. The reason is that, when profiling using JSONL, roughly 75% of the run time of the calculations I'm running is simply SerDe Deserialize operations. The reason I chose JSONL is because I can stream line by line from a Gzipped JSON file, so I do not have to load large datasets into memory before operating. 

I'm curious, since I'm new to Avro and I haven't seen streaming examples in the README for avro-rs (it's probably a strange usecase), how one would go about Streaming data from an Avro file using this library? I can't seem to find documentation to point out when I've reached the end of one data point in the file and the start of the next data point.

Could someone help point me in the right direction? I'm also on the Rust discord, so if it's easier to have a conversation there (and then document that conversation here after), I'd greatly appreciate the help!

- Stu

**Comment by poros** [comment]
Hi @stuartweir , I don't know much of the streaming use case you have in mind so I am a bit shooting in the dark here.

Avro has this concept of Writer which is an abstraction on top of a I/O buffer. You can append one value (or record, if you want to use an actual avro record) at the time and avro will encode it and periodically flush it to the buffer. If that's what you are looking for in your streaming use case (I read processing a JSON file line by line) perhaps avro will work for you.

I must warn you that avro serde is pretty heavy on the CPU because avro has many more features of json and it does perform decently efficient binary encoding and, above all, schema validation. So I would say that the format weights features and correctness over performance.

I hope that this is enough to get you started if this is what you are looking for or to steer you away from avro before you spend any more time with it (:

**Comment by poros** [comment]
Oh yes, I forgot to mention that also the reading happens one block at the time through the Reader interface, so you won't have to load the entire file in memory.

**Comment by stuartweir** [comment]
Hi @poros, thank you so much for your help! That does indeed help me out, and I'll take that into consideration when I try to compare between JSONL and Avro.
